services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      APP_NAME_O2SWITCH: test_python
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      DB_HOST: db
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_NAME: accueillants
    depends_on:
      - db
  db:
    image: postgres:15 # You can use a different PostgreSQL version
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: accueillants
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose port 5432 on your host
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080" # Expose port 8080 on your host
    depends_on:
      - db
volumes:
  db_data:


