version: "3.8"
services:
  db:
    image: postgres:15 # You can use a different PostgreSQL version
    restart: always
    environment:
      POSTGRES_USER: jilu3758_admin
      POSTGRES_PASSWORD: v~8J*hJBmm[f
      POSTGRES_DB: jilu3758_accueillants
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose port 5432 on your host
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080" # Expose port 8080 on your host
    depends_on:
      - db
volumes:
  db_data:


